sudo: required
dist: trusty
group: edge

language: go
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master

matrix:
    allow_failures:
        - go: master


install:
    - go get -v golang.org/x/tools/cmd/cover
    - sudo add-apt-repository -y ppa:opencpu/opencpu-1.6
    - sudo apt-get update
    - sudo apt-get upgrade -y
    - sudo apt-get install -y opencpu-server
    - sudo apt-get install libapparmor-dev
    - curl https://cran.r-project.org/src/contrib/semver_0.2.0.tar.gz -o semver_0.2.0.tar.gz
    - sudo R CMD INSTALL semver_0.2.0.tar.gz

script:
    - go test -v
    - . .travis/install-opencpu-2.0
    - go test -v -covermode=count -coverprofile=profile.cov

after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
