language: go
go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip
install:
    - go get -v golang.org/x/tools/cmd/cover
script:
    - go test -v -covermode=count -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
